name: mi_aguila
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  intl: ^0.17.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  location: ^3.2.4 
  permission_handler: ^5.1.0+2
  location_permissions: ^3.0.0+1
  google_maps_flutter: ^1.2.0
  very_good_analysis: ^2.0.0
  cupertino_icons: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  